entutor.i18n={
    'testbutton': 'Готово',
    'nextbutton': 'Далее',
    'restartbutton': 'Начать задание заново',
    'Presentation':'Презентация',
    'CSS classes':'Классы CSS',
    'Arrange subelements':'Выстроить подэлементы',
    'Hint':'Подсказка',
    'Precondition':'Условие показа',
    'Autocheck':'Автоматическая проверка',
    'Task Pass Score':'Минимальный зачётный балл',
    'Max Score':'Максимальный балл',
    'Hide if Correct':'Скрыть, если зачтено',
    'horizontal':'Горизонтально',
    'vertical':'Вертикально',
    'flow':'Поток',
    'Duration, seconds':'Длительность, секунд',
    'Animation Frame':'Кадр анимации',
    'type correct answer here':'на печатайте ответ',
    'Correct value*':'Правильный ответ*',
    'Initial value':'Начальное значение',
    'Correct values<br>(one per string)':'Правильные ответы<br>(один ответ в строке)',
    'Test rule':'Правило проверки',
    'Width':'Ширина',
    'Accept multiple counters':'Принимать несколько фишек',
    'Eject counter on error':'Очистить, если ошибка',
    'Autostart':'Автоматический старт',
    'Require Complete View':'Требовать полного просмотра',
    'WEBMV file URL':'Адрес файла WEBMV',
    'OGV file URL':'Адрес файла OGV',
    'M4V file URL':'Адрес файла M4V',
    'Subtitle':'Субтитр',
    'Sound title':'Название звука',
    'MP3 file URL':'Адрес файла MP3',
    'OGA file URL':'Адрес файла OGA',
    'WAV file URL':'Адрес файла WAV',
    'Slide':'Слайд',
    'From time':'От времени',
    'To time':'До времени',
    'Min score to pass (0 ... 1)':'Минимальный счёт для зачёта(0 ... 1)',
    'beforeCorrect':'Предыдущий блок зачтён',
    'none':'',
    'Maximal length':'Максимальная длина',
    'Reset if Error':'Очистить при ошибке',
    'type checkbox label here':'напечатайте здесь метку',
    'type visible text here':'напечатайте здесь видимый текст',
    'Value provided to dropzone':'Значение, передаваемое в зону для оценки',
    'testSet':'Как множество',
    'testSequence':'Как последовательность',
    'mp3 file URL':'Адрес файла mp3',
    'oga file URL':'Адрес файла oga',
    'wav file URL':'Адрес файла wav',
    'm4v file URL':'Адрес файла m4v',
    'ogv file URL':'Адрес файла ogv',
    'webmv file URL':'Адрес файла webmv',
    'Video title':'Название видео',
    'Initial seqence':'Начальная последовательность',
    'card':'карточка',
    'html':'html',
    'text':'текст',
    'radio':'радиокнопка',
    'checkbox':'флажок',
    'counter':'фишка',
    'dropzone':'dropzone',
    'sound':'звук',
    'video':'видео',
    'playlist':'плейлист',
    'slideshow':'слайды',
    'recorder':'микрофон',
    'sequence':'последовательность'
};
